### ISSUE TITLE
example in Javascript

### ISSUE THREAD

**Issue by donstivino** [PAYONE-GmbH/Simple-PHP-Integration#2]
Hallo,

i try to integrate Payone in Reactjs app but without success. i receive all the time this error:
"Hashwert nicht korrekt".
Please do you have any examples with JavaScript?

Best Regards

**Comment by T-Kuchel** [comment]
Hi @donstivino ,

have a look at https://docs.payone.com/display/public/PLATFORM/CA+-+Calculation+of+the+HASH+value
There is a little example in PHP maybe this help you to go further with your JavaScript.

Greeting from Kiel
Timo
